# Generated by Django 4.0.1 on 2025-05-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('descrip', models.CharField(max_length=20)),
                ('ingrediants', models.CharField(max_length=30)),
                ('pim', models.FileField(upload_to='pic')),
                ('instructions', models.CharField(max_length=30)),
            ],
        ),
    ]
