# Generated by Django 4.0.1 on 2025-05-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_tbl',
            old_name='pim',
            new_name='pic',
        ),
    ]
