# Generated by Django 4.0.1 on 2025-05-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_pim_add_tbl_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_tbl',
            old_name='descrip',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='add_tbl',
            old_name='pic',
            new_name='image',
        ),
    ]
