# Generated by Django 4.0.1 on 2025-05-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_descrip_add_tbl_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_tbl',
            name='description',
            field=models.TextField(),
        ),
    ]
