# Generated by Django 4.0.1 on 2025-05-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_add_tbl_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_tbl',
            name='instructions',
            field=models.CharField(max_length=200),
        ),
    ]
